#!/bin/sh

export ZSH="$(cd "$(dirname "$0")/.." && pwd -P)"

# Source helper functions
. $ZSH/ai/helpers/output.sh
. $ZSH/ai/helpers/json-settings.sh

info "Configuring MCP permissions…"

SETTINGS_FILE="$HOME/.claude/settings.json"

# Define comprehensive MCP permissions configuration
# Auto-approve safe read-only operations while requiring approval for write/dangerous operations
PERMISSIONS_CONFIG=$(cat <<'EOF'
{
  "permissions": {
    "defaultMode": "auto",
    "allow": [
      "Bash(* > /tmp/*)",
      "Bash(./bin/fmt:*)",
      "Bash(./bin/ruff.sh:*)",
      "Bash(DJANGO_SETTINGS_MODULE=:* mypy::*)",
      "Bash(DJANGO_SETTINGS_MODULE=:* python -m pytest::*)",
      "Bash(DJANGO_SETTINGS_MODULE=:*)",
      "Bash(NOW=:*)",
      "Bash(SINCE=:*)",
      "Bash([ -d :*)",
      "Bash([ -e :*)",
      "Bash([ -f :*)",
      "Bash(awk:*)",
      "Bash(bash:*)",
      "Bash(bin/fmt:*)",
      "Bash(bin/ruff.sh:*)",
      "Bash(brew info:*)",
      "Bash(brew list:*)",
      "Bash(cargo --version:*)",
      "Bash(cargo :*)",
      "Bash(cargo bench:*)",
      "Bash(cargo build:*)",
      "Bash(cargo cache:*)",
      "Bash(cargo check:*)",
      "Bash(cargo clean:*)",
      "Bash(cargo clippy :* 2>&1 | head::*)",
      "Bash(cargo clippy :* 2>&1::*)",
      "Bash(cargo clippy:*)",
      "Bash(cargo doc:*)",
      "Bash(cargo fmt:*)",
      "Bash(cargo install:*)",
      "Bash(cargo run:*)",
      "Bash(cargo shear:*)",
      "Bash(cargo sweep:*)",
      "Bash(cargo test :* 2>&1::*)",
      "Bash(cargo test:*)",
      "Bash(cargo tree:*)",
      "Bash(cargo update:*)",
      "Bash(cat:*)",
      "Bash(cd :* && cargo build::*)",
      "Bash(cd :* && cargo check::*)",
      "Bash(cd :* && cargo clippy :* 2>&1 | head::*)",
      "Bash(cd :* && cargo clippy :* 2>&1::*)",
      "Bash(cd :* && cargo clippy::*)",
      "Bash(cd :* && cargo fmt::*)",
      "Bash(cd :* && cargo shear::*)",
      "Bash(cd :* && cargo test :* 2>&1::*)",
      "Bash(cd :* && cargo test::*)",
      "Bash(cd :* && cargo:*)",
      "Bash(chmod:*)",
      "Bash(claude:*)",
      "Bash(curl:*)",
      "Bash(date:*)",
      "Bash(docker compose:*)",
      "Bash(docker network:*)",
      "Bash(echo:*)",
      "Bash(find:*)",
      "Bash(flox activate -- bash -c :*bin/fmt:*)",
      "Bash(flox activate -- bash -c :*mypy:*)",
      "Bash(flox activate -- bash -c :*pytest:*)",
      "Bash(flox activate -- bash -c :*ruff:*)",
      "Bash(flox activate --:*)",
      "Bash(flox activate:*)",
      "Bash(gawk:*)",
      "Bash(gh api:*)",
      "Bash(gh auth status:*)",
      "Bash(gh issue list:*)",
      "Bash(gh issue view:*)",
      "Bash(gh pr checkout:*)",
      "Bash(gh pr checks:*)",
      "Bash(gh pr create:*)",
      "Bash(gh pr diff:*)",
      "Bash(gh pr list:*)",
      "Bash(gh pr status:*)",
      "Bash(gh pr view:*)",
      "Bash(gh release list:*)",
      "Bash(gh release view:*)",
      "Bash(gh repo clone:*)",
      "Bash(gh repo fork:*)",
      "Bash(gh repo list:*)",
      "Bash(gh repo view:*)",
      "Bash(gh run list:*)",
      "Bash(gh run view:*)",
      "Bash(gh run watch:*)",
      "Bash(gh search:*)",
      "Bash(gh status:*)",
      "Bash(gh workflow list:*)",
      "Bash(gh workflow view:*)",
      "Bash(git --version:*)",
      "Bash(git add:*)",
      "Bash(git blame:*)",
      "Bash(git branch:*)",
      "Bash(git check-ignore:*)",
      "Bash(git checkout:*)",
      "Bash(git cherry-pick:*)",
      "Bash(git commit:*)",
      "Bash(git config:*)",
      "Bash(git diff:*)",
      "Bash(git fetch:*)",
      "Bash(git log:*)",
      "Bash(git merge:*)",
      "Bash(git pull:*)",
      "Bash(git rebase:*)",
      "Bash(git reflog:*)",
      "Bash(git remote:*)",
      "Bash(git reset:*)",
      "Bash(git rev-list:*)",
      "Bash(git rev-parse:*)",
      "Bash(git shortlog:*)",
      "Bash(git show:*)",
      "Bash(git stash:*)",
      "Bash(git status:*)",
      "Bash(git switch:*)",
      "Bash(git tag:*)",
      "Bash(git worktree:*)",
      "Bash(grep:*)",
      "Bash(head:*)",
      "Bash(ln:*)",
      "Bash(ls:*)",
      "Bash(markdownlint:*)",
      "Bash(mkdir:*)",
      "Bash(mypy --version && mypy -p posthog | mypy-baseline filter:*)",
      "Bash(mypy .)",
      "Bash(mypy:*)",
      "Bash(node:*)",
      "Bash(npm:*)",
      "Bash(npx:*)",
      "Bash(openssl:*)",
      "Bash(osascript:*)",
      "Bash(pbcopy:*)",
      "Bash(pip3:*)",
      "Bash(pip:*)",
      "Bash(pnpm:*)",
      "Bash(pyenv:*)",
      "Bash(pytest:*)",
      "Bash(python -c:*)",
      "Bash(python -m mypy:*)",
      "Bash(python -m pytest:*)",
      "Bash(python3:*)",
      "Bash(python:*)",
      "Bash(redis-cli:*)",
      "Bash(ruff check:*)",
      "Bash(ruff format:*)",
      "Bash(ruff:*)",
      "Bash(sed:*)",
      "Bash(snob:*)",
      "Bash(sort:*)",
      "Bash(source:*)",
      "Bash(ssh:*)",
      "Bash(swift:*)",
      "Bash(tail:*)",
      "Bash(test -d :*)",
      "Bash(test -e :*)",
      "Bash(test -f :*)",
      "Bash(tmux:*)",
      "Bash(wc:*)",
      "Bash(which:*)",
      "Bash(xargs:*)",
      "Bash(xattr:*)",
      "Bash(zsh:*)",
      "Bash(~/.claude/bin/*:*)",
      "Bash(~/.claude/skills/*:*)",
      "Fetch(*)",
      "Read(//Users/richard/dev/**)",
      "Read(/tmp/**)",
      "Read(~/.claude/**)",
      "WebFetch(domain:*)",
      "WebSearch",
      "mcp__github__get_file_contents",
      "mcp__github__get_issue",
      "mcp__github__get_pull_request",
      "mcp__github__get_pull_request_comments",
      "mcp__github__get_pull_request_files",
      "mcp__github__get_pull_request_reviews",
      "mcp__github__get_pull_request_status",
      "mcp__github__list_commits",
      "mcp__github__list_issues",
      "mcp__github__list_pull_requests",
      "mcp__github__search_code",
      "mcp__github__search_issues",
      "mcp__github__search_repositories",
      "mcp__github__search_users",
      "mcp__google-calendar__get-current-time",
      "mcp__google-calendar__get-event",
      "mcp__google-calendar__get-freebusy",
      "mcp__google-calendar__list-calendars",
      "mcp__google-calendar__list-events",
      "mcp__google-calendar__search-events",
      "mcp__grafana__list_datasources",
      "mcp__grafana__list_loki_label_names",
      "mcp__grafana__list_loki_label_values",
      "mcp__grafana__query_loki_logs",
      "mcp__grafana__query_prometheus",
      "mcp__memory__open_nodes",
      "mcp__memory__read_graph",
      "mcp__memory__search_nodes",
      "mcp__posthog-db__*",
      "mcp__posthog-db__analyze_db_health",
      "mcp__posthog-db__analyze_query_indexes",
      "mcp__posthog-db__analyze_workload_indexes",
      "mcp__posthog-db__execute_sql",
      "mcp__posthog-db__explain_query",
      "mcp__posthog-db__get_object_details",
      "mcp__posthog-db__get_top_queries",
      "mcp__posthog-db__list_objects",
      "mcp__posthog-db__list_schemas",
      "mcp__puppeteer__puppeteer_navigate",
      "mcp__puppeteer__puppeteer_screenshot",
      "mcp__slack__channels_list",
      "mcp__slack__conversations_history",
      "mcp__slack__conversations_replies",
      "mcp__slack__conversations_search_messages"
    ]
  }
}
EOF
)

merge_json_settings "$SETTINGS_FILE" "$PERMISSIONS_CONFIG" "MCP permissions"
case $? in
    0)
        success "Safe tool operations auto-approved"
        info "Write/dangerous operations will still require approval:"
        info "  - GitHub: create/update/merge operations"
        info "  - Memory: create/delete operations"
        info "  - Git: push operations (add/commit/read operations are auto-approved)"
        info "  - GitHub CLI: create/merge operations (read operations are auto-approved)"
        ;;
    2)
        success "Tool permissions already configured"
        ;;
esac
